#!/bin/bash
#ngt gen

#Generate ngt files

#chromosome marker 0 position indicator
#indicator = 1 if genotyped, 0 if not.

cd /home/pgcdac/DWFV2CJb8Piv_0116_pgc_data/pts/wave2/v1
for study in $(ls | grep -v ancestry_stratified )
do

mkdir "$study"/temporary_files
mkdir "$study"/ngt
#sort the genotype file by marker
genotype_file=$(ls "$study"/qc | grep .bim)
awk '{print $2}' "$study"/qc/"$genotype_file" | LC_ALL=C sort -k1,1b > "$study"/temporary_files/genotyped_markers.txt


for file in $(ls "$study"/qc1 | grep .map)
do
 #remove .map from filename
 outname=$(echo $file | sed 's/.map//g')
 
 #Take unjoined, put a 0 at the enend
 LC_ALL=C join -v 1 <(awk '{print $2,$1,$3,$4,0}' "$study"/qc1/"$file" | LC_ALL=C sort -k1,1b ) "$study"/temporary_files/genotyped_markers.txt | awk '{print $2,$1,$3,$4,$5}'  > "$study"/temporary_files/"$outname"_uj.ngt
 
 #Take joined, put a 1 at the end
 LC_ALL=C join <(awk '{print $2,$1,$3,$4,1}' "$study"/qc1/"$file" | LC_ALL=C sort -k1,1b ) "$study"/temporary_files/genotyped_markers.txt | awk '{print $2,$1,$3,$4,$5}'  > "$study"/temporary_files/"$outname"_j.ngt
 
 cat "$study"/temporary_files/"$outname"_uj.ngt temporary_files/"$outname"_j.ngt | sort -g -k4 > "$study"/ngt/"$outname".ngt
 
 mv "$study"/ngt/* "$study"/qc1/.
 
done
# mkdir errandout
#sbatch --time=00:60:00 --error errandout/ngtgen.e --output errandout/ngtgen.o 
